### ISSUE TITLE
Search Their Entries

### ISSUE THREAD

**Issue by daisyyoo** [daisyyoo/code-journal#9]
## 💰 Motivation

Coders will want to be able to search through their entries to find their previous ones.

## 📐 Plan

Create a search box that shows the entries that match.

## ✅ Task List

- [x] Create a search box on right side of header
- [ ] Outline purple when focused
- [ ] Update value of input text as user types and searches for entry
- [ ] Show matching entries below the search box
- [ ] When user clicks the entry in search box results, the user should be led to that entry on the entries page.
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ] Test all functionality again in a private browsing session.
- [ ] Fix all errors.
